version: '3.7'

services:
  apache:
    image: przemr/apache 
    ports:
      - 6666:80
    networks: 
      - frontend
      - backend
    volumes:
      - ./documents:/usr/local/apache2/htdocs
    depends_on:
      - php
      - mysql
    deploy:
     replicas: 2
     restart_policy:
      condition: on-failure
  php:
    image: przemr/php
    networks: 
      - backend
    volumes:
      - ./documents:/usr/local/apache2/htdocs
    deploy: 
     replicas: 2
     restart_policy:
      condition: on-failure
  mysql:
    image: przemr/mysql
    networks:
      - backend
    volumes:
      - dbmysql:/var/lib/mysql
    deploy:
     replicas: 1
     placement:
      constraints: [node.role == manager]
     restart_policy:
      condition: on-failure
volumes:
  dbmysql:
networks: 
  backend:
  frontend:
