version: '3.7'

services:
  apache:
    build: 
     context: './apache-service'
     dockerfile: Dockerfile-apache
    restart: always
    ports:
      - 6666:80
    networks: 
      - frontend
      - backend
    volumes:
      - ./documents:/usr/local/apache2/htdocs
    depends_on:
      - php
      - mysql
  php:
    build: 
     context: './php-service'
     dockerfile: Dockerfile-php
    restart: always
    networks: 
      - backend
    volumes:
      - ./documents:/usr/local/apache2/htdocs
  mysql:
    build: 
     context: './mysql-service'
     dockerfile: Dockerfile-mysql
    restart: always
    networks:
      - backend
    volumes:
      - ./database:/var/lib/mysql
networks: 
  backend:
  frontend:
